// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	DeleteAuthor(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
